### ISSUE TITLE
panic: label value "\xb6\xa6\xbc\xce" is not valid UTF-8

### ISSUE THREAD

**Issue by bubbleatgit** [hatamiarash7/Mikrotik-Exporter#1]
```
{"level":"info","msg":"Welcome to Mikrotik Prometheus Exporter","time":"2020-07-10T01:33:38+08:00"}
{"level":"info","msg":"Version: 1.2","time":"2020-07-10T01:33:38+08:00"}
{"level":"info","msg":"Setting up collector for devices","numDevices":1,"time":"2020-07-10T01:33:38+08:00"}
{"level":"info","msg":"Listening on :9436","time":"2020-07-10T01:33:38+08:00"}
panic: label value "\xb6\xa6\xbc\xce" is not valid UTF-8

goroutine 11 [running]:
github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
	/root/go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/value.go:102
mikrotik-exporter/collector.(*ipsecCollector).collectMetricForProperty(0xc00022a340, 0x95c12e, 0x9, 0xc0001351c0, 0x1f, 0xc0001b1188, 0x4, 0xc000109d00, 0xc000137a60)
	/mnt/e/Github/Mikrotik-Exporter/collector/ipsec_collector.go:108 +0x80d
mikrotik-exporter/collector.(*ipsecCollector).collectForStat(0xc00022a340, 0xc000109d00, 0xc000137a60)
	/mnt/e/Github/Mikrotik-Exporter/collector/ipsec_collector.go:70 +0x222
mikrotik-exporter/collector.(*ipsecCollector).collect(0xc00022a340, 0xc000137a60, 0x0, 0x0)
	/mnt/e/Github/Mikrotik-Exporter/collector/ipsec_collector.go:46 +0x86
mikrotik-exporter/collector.(*collector).connectAndCollect(0xc000078680, 0xc00006e980, 0xc00005c7e0, 0x0, 0x0)
	/mnt/e/Github/Mikrotik-Exporter/collector/collector.go:320 +0x14b
mikrotik-exporter/collector.(*collector).collectForDevice(0xc000078680, 0xc00002a4e0, 0x16, 0xc000028160, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/mnt/e/Github/Mikrotik-Exporter/collector/collector.go:291 +0xdc
mikrotik-exporter/collector.(*collector).Collect.func1(0xc000078680, 0xc00005c7e0, 0xc000028f30, 0xc00002a4e0, 0x16, 0xc000028160, 0xd, 0x0, 0x0, 0x0, ...)
	/mnt/e/Github/Mikrotik-Exporter/collector/collector.go:256 +0x7d
created by mikrotik-exporter/collector.(*collector).Collect
	/mnt/e/Github/Mikrotik-Exporter/collector/collector.go:255 +0x2f2

```

**Comment by hatamiarash7** [comment]
Please share your `config.yml` file or environment variables

**Comment by bubbleatgit** [comment]
Thanked your reply.
this is my `config.yml`

```
devices:
  - name: JLPAYBUILDING-MIKROTIK
    address: 172.20.31.254
    user:  prometheus
    password: w30DOuEK3ioyVMGJPSVd

features:
  bgp: true
  dhcp: true
  dhcpv6: true
  dhcpl: true
  routes: true
  pools: true
  optics: true
  wlansta: true
  wlanif: true
  ipsec: true

```
