### ISSUE TITLE
Cannot read property 'result' of undefined

### ISSUE THREAD

**Issue by elcidowneador** [hatamiarash7/Mikrotik-Exporter#6]
Hi,

I have imported Mikrotik dashboard for Grafana and also configured Prometheus as Data Source pointing to container but i'm seeing this error. If i go to http://ip:9436/metrics i can see the metrics, so i don't understand why is showing this error.

Could you help, please?

![Screenshot 2020-08-06 at 12 57 59](https://user-images.githubusercontent.com/48317223/89524244-83161800-d7e4-11ea-92c2-fdf9bbf0e35c.png)

**Comment by hatamiarash7** [comment]
Please share your prometheus config file.

you can go to http://ip:9090 and check prometheus targets

**Comment by elcidowneador** [comment]
Sorry mate but what service are you refering? i mean, i have Grafana in :3000 and Prometheus in :9436. If i go to Prometheus, i only see a link to access to the metrics from Prometheus.

**Comment by hatamiarash7** [comment]
Sorry ... Typographical mistakes :)

Go to `Prometheus dashboard` from http://ip:9436 and check your targets

![Screenshot_20200806_224357](https://user-images.githubusercontent.com/16325641/89567218-89cd7b00-d836-11ea-909d-9e9cc6bd89a2.png)

**Comment by elcidowneador** [comment]
No problem!

I checked targets of Prometheus and so i discovered the problem for the main issue (Exporter are not appearing) 

Now i can't see any error but don't see any data, look:

![Screenshot 2020-08-06 at 12 19 48](https://user-images.githubusercontent.com/48317223/89575939-cbf2be80-d82e-11ea-8fc9-6e7cd2965103.png)

But if go to the metrics of Mikrotik exporter, i cant see data and also in target i can see data is sourced by Prometheus. Any other idea?

**Comment by hatamiarash7** [comment]
You should select `Node`

![Screenshot_2020-08-07 Mikrotik - Grafana](https://user-images.githubusercontent.com/16325641/89641478-fd1ecd80-d8c6-11ea-9855-a39c43d4d46a.png)

**Comment by elcidowneador** [comment]
Hmmm, very strange, node appears empty

<img width="237" alt="Screenshot 2020-08-07 at 18 15 24" src="https://user-images.githubusercontent.com/48317223/89666138-2137da00-d8da-11ea-950b-932a594a2f22.png">

**Comment by hatamiarash7** [comment]
Check your Prometheus ... share it please

**Comment by elcidowneador** [comment]
Sure!

```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
```

**Comment by hatamiarash7** [comment]
You have not any job for `mikrotik` ... You should have something like this : 

```yaml
scrape_configs:
- job_name: mikrotik
  static_configs:
  - targets:
    - localhost:9436
```
